### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by shevegen** [gobolinux/GoboNet#2]
I do not yet know the new GoboNet.

Is there something for the end user to know about it in regards to using it?

I see that the shell file has functions such as show_dialog() and also some
other embedded help options such as  **gobonet connect "<network>"**.

Would you think that a short example file (doc file, perhaps .md) may be 
useful to have? Or should people rather just use the help section of the
shell script. Feel free to close this issue at your leisure. :)

**Comment by hishamhm** [comment]
The main intended UI for end-users is the AwesomeWM widget included in Gobo 016. The GoboNet package, by itself, is a simple command-line tool (which the widget uses).

There's not much to it beyond what the main script shows in the help screen. Adding that info to README.md would be a good idea, yes. But essentially, to use Wifi from the command-line it's a matter of using `gobonet list` to see the networks and `gobonet connect "My Network Name"` to connect.
